import { defineSchema, defineTable } from "convex/server";
import { authTables } from "@convex-dev/auth/server";
import { v } from "convex/values";

// The data model is split by provenance rather than by feature, because the
// analysis layer has to be able to say where every number came from:
//
//   dailyLogs    self-reported   typed in by the user, subjective, can be wrong
//   githubDaily  measured        fetched from the GitHub API, objective
//   syncRuns     audit           when ingestion ran, what it wrote, did it fail
//
// Nothing writes to both dailyLogs and githubDaily, so a row can never be a
// silent mix of the two. analytics.js joins them on (userId, date) and tags
// each field with its source when it builds the analysis dataset.
export default defineSchema({
  ...authTables,

  // Extends Convex Auth's built-in users table (name, image, email,
  // emailVerificationTime, phone, phoneVerificationTime, isAnonymous)
  // with our app-specific field. githubUsername is normally filled in
  // automatically from the GitHub profile on first sign-in (see
  // convex/auth.ts), but stays user-editable as a fallback/override.
  users: defineTable({
    name: v.optional(v.string()),
    image: v.optional(v.string()),
    email: v.optional(v.string()),
    emailVerificationTime: v.optional(v.number()),
    phone: v.optional(v.string()),
    phoneVerificationTime: v.optional(v.number()),
    isAnonymous: v.optional(v.boolean()),
    githubUsername: v.optional(v.string()),
    wakatimeApiKey: v.optional(v.string()),
    // Minutes AHEAD of UTC (Yangon = +390). Note this is the negation of
    // JavaScript's Date.getTimezoneOffset(), which counts the other way — the
    // sign is flipped at the call site so the stored value reads naturally.
    //
    // Commit timestamps arrive from GitHub in UTC. Bucketing them by UTC hour
    // mislabels a Yangon developer's whole day by 6.5 hours: 20:00 local lands
    // in the "afternoon" bucket, so "when do you code" comes out backwards.
    timezoneOffsetMinutes: v.optional(v.number()),
  })
    .index("email", ["email"])
    .index("phone", ["phone"]),

  // LAYER 1a — self-reported. Only things GitHub can never tell us.
  dailyLogs: defineTable({
    userId: v.id("users"),
    date: v.string(), // ISO date, e.g. "2026-08-07"
    // Optional because it's a fallback: once WakaTime is connected, the
    // dashboard stops asking for this (WakaTime's measured figure wins in
    // analytics.buildDataset — see the comment there), so new rows from a
    // connected user simply won't carry it.
    codingHours: v.optional(v.number()),
    sleepHours: v.number(),
    coffeeIntake: v.number(),
    aiToolUsageMinutes: v.number(),
    problemsSolved: v.number(),
    taskDifficulty: v.number(), // 1-5
    experienceLevel: v.number(), // 1-5
    programmingScore: v.number(), // 1-10
    // Synthetic rows generated by seed.js. Every query that feeds a chart or a
    // statistic carries this through so demo data can never be presented as
    // if it were really observed.
    isSeeded: v.optional(v.boolean()),
    updatedAt: v.optional(v.number()),
  })
    .index("by_user_and_date", ["userId", "date"])
    .index("by_user", ["userId"]),

  // LAYER 1b — measured. Written only by convex/github.js.
  githubDaily: defineTable({
    userId: v.id("users"),
    date: v.string(),
    commits: v.number(),
    pullRequestsOpened: v.number(),
    issuesOpened: v.number(),
    reviews: v.number(),
    // Only present once a detailed sync has run for this day — the
    // contributions calendar gives counts but not diffs or timestamps.
    //
    // additions/deletions exclude generated files (lockfiles, node_modules,
    // build output — see lib/commitFiles.js). The unfiltered figures are kept
    // as *Raw so the cleaning step can be shown rather than just asserted.
    additions: v.optional(v.number()),
    deletions: v.optional(v.number()),
    additionsRaw: v.optional(v.number()),
    deletionsRaw: v.optional(v.number()),
    filesChanged: v.optional(v.number()),
    filesExcluded: v.optional(v.number()),
    reposTouched: v.optional(v.number()),
    commitsByBucket: v.optional(
      v.object({
        night: v.number(), // 00:00–05:59
        morning: v.number(), // 06:00–11:59
        afternoon: v.number(), // 12:00–17:59
        evening: v.number(), // 18:00–23:59
      }),
    ),
    // "calendar"  — GraphQL contributionsCollection, counts only
    // "detailed"  — REST commits walk, includes diffs and timestamps
    // "migrated"  — carried over from the old self-reported githubCommits field
    detailLevel: v.union(v.literal("calendar"), v.literal("detailed"), v.literal("migrated")),
    fetchedAt: v.number(),
  })
    .index("by_user_and_date", ["userId", "date"])
    .index("by_user", ["userId"]),

  // LAYER 1c — measured. Written only by convex/wakatime.js. Kept apart from
  // dailyLogs.codingHours for the same reason githubDaily is kept apart from
  // it: this is fetched from an external API, not typed in.
  wakatimeDaily: defineTable({
    userId: v.id("users"),
    date: v.string(),
    codingSeconds: v.number(),
    languages: v.optional(v.array(v.object({ name: v.string(), seconds: v.number() }))),
    // Longest unbroken coding stretch that day, from WakaTime's Durations API
    // (heartbeat blocks merged across gaps under 15 minutes). Optional because
    // it comes from a second, best-effort request per day — a summaries-only
    // sync (or one where a single day's durations call failed) still has
    // codingSeconds without this.
    longestSessionMinutes: v.optional(v.number()),
    fetchedAt: v.number(),
  })
    .index("by_user_and_date", ["userId", "date"])
    .index("by_user", ["userId"]),

  // LAYER 2 — ingestion audit. Every backfill/sync appends one row, including
  // failures, so the dataset's coverage is explainable after the fact.
  syncRuns: defineTable({
    userId: v.id("users"),
    kind: v.union(
      v.literal("calendar"),
      v.literal("detailed"),
      v.literal("migration"),
      v.literal("wakatime"),
    ),
    startDate: v.string(),
    endDate: v.string(),
    daysWritten: v.number(),
    status: v.union(v.literal("ok"), v.literal("error")),
    message: v.optional(v.string()),
    ranAt: v.number(),
  }).index("by_user", ["userId"]),
});
