// Which files in a commit count as work the developer actually did.
//
// Raw GitHub diff stats are close to useless as a productivity signal: a single
// `npm install` commit can carry a million-line lockfile diff and swamp a
// year of real editing. Measured on this project's own history, 91 commits
// reported 3.19M added / 1.65M deleted lines — around 35,000 lines per commit.
//
// So additions/deletions are summed only over files that pass this filter, and
// the unfiltered totals are stored alongside as additionsRaw/deletionsRaw so
// the effect of the cleaning step stays visible and auditable.

// Directories whose contents are installed or generated, never hand-written.
const EXCLUDED_DIR_SEGMENTS = [
  "node_modules",
  "vendor",
  "bower_components",
  "dist",
  "build",
  "out",
  "target", // rust / java
  "coverage",
  ".next",
  ".nuxt",
  ".svelte-kit",
  ".output",
  "__pycache__",
  "_generated", // convex, protobufs
  "generated",
  "migrations/versions", // alembic autogenerated
];

// Dependency lockfiles. Machine-written, frequently enormous.
const EXCLUDED_BASENAMES = new Set([
  "package-lock.json",
  "yarn.lock",
  "pnpm-lock.yaml",
  "bun.lock",
  "bun.lockb",
  "composer.lock",
  "gemfile.lock",
  "poetry.lock",
  "pdm.lock",
  "cargo.lock",
  "go.sum",
  "packages.lock.json",
  "podfile.lock",
  "mix.lock",
  "flake.lock",
]);

// Compiled, minified or otherwise machine-emitted file shapes.
const EXCLUDED_PATTERNS = [
  /\.min\.(js|css)$/i,
  /\.map$/i, // source maps
  /\.gen\.(ts|js|go)$/i, // routeTree.gen.ts and friends
  /\.pb\.(go|js|ts)$/i, // protobuf
  /_pb2\.py$/i,
  /\.snap$/i, // jest snapshots
  /\.(png|jpe?g|gif|webp|avif|ico|svg|pdf|mp4|mov|woff2?|ttf|eot|otf|zip|gz|tar|jar|so|dll|dylib|exe|bin|wasm)$/i,
];

// GitHub's commit endpoint returns at most 300 file entries. Past that the diff
// stats we compute are a floor, not a total — callers surface this rather than
// presenting a truncated sum as complete.
export const GITHUB_FILE_LIST_LIMIT = 300;

export function isGeneratedFile(filename) {
  if (!filename) return true;
  const path = filename.toLowerCase();
  const segments = path.split("/");
  const basename = segments[segments.length - 1];

  // Any path segment being an excluded directory disqualifies the file, so
  // "packages/web/node_modules/x" is caught as well as "node_modules/x".
  for (const segment of segments.slice(0, -1)) {
    if (EXCLUDED_DIR_SEGMENTS.includes(segment)) return true;
  }
  if (EXCLUDED_BASENAMES.has(basename)) return true;
  return EXCLUDED_PATTERNS.some((pattern) => pattern.test(basename));
}

// Splits a commit's file list into authored vs generated and totals each side.
//
// `files` is GitHub's commit.files array; when it is absent (the endpoint omits
// it for very large commits) there is nothing to attribute, so the authored
// totals are reported as zero with filesTruncated set — silently falling back
// to the raw stats would reintroduce exactly the distortion this removes.
export function summarizeCommitFiles(files, stats) {
  const rawAdditions = stats?.additions ?? 0;
  const rawDeletions = stats?.deletions ?? 0;

  if (!Array.isArray(files)) {
    return {
      additions: 0,
      deletions: 0,
      rawAdditions,
      rawDeletions,
      filesChanged: 0,
      filesExcluded: 0,
      filesTruncated: true,
    };
  }

  let additions = 0;
  let deletions = 0;
  let filesChanged = 0;
  let filesExcluded = 0;

  for (const file of files) {
    if (isGeneratedFile(file.filename)) {
      filesExcluded++;
      continue;
    }
    additions += file.additions ?? 0;
    deletions += file.deletions ?? 0;
    filesChanged++;
  }

  return {
    additions,
    deletions,
    rawAdditions,
    rawDeletions,
    filesChanged,
    filesExcluded,
    filesTruncated: files.length >= GITHUB_FILE_LIST_LIMIT,
  };
}
